version: "3"
services:
  web:
    image: ameerabdulaziz/portfolio
    container_name: portfolio_web
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: python manage.py runserver 0.0.0.0:8000

  nginx:
    image: nginx
    container_name: portfolio_nginx
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    depends_on:
      - web