# Generated by Django 3.0.4 on 2020-03-16 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='icon',
            field=models.CharField(default='', max_length=120),
            preserve_default=False,
        ),
    ]
