# Generated by Django 3.0.4 on 2020-03-17 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20200317_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='field',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='resume.Field'),
            preserve_default=False,
        ),
    ]
