name: Push-to-EC2

on:
  push:
    branches:
      - master


jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest

  steps:
    - name: Checkout the files
      uses: actions/checkout@v2
  
    - name: Deploy to Server 1
      uses: ameerabdulaziz/portfolio@master
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
        REMOTE_HOSY: ${{ secrets.HOST_DNS }}
        REMOTE_USER: ${{ secrets.USERNAME }}
        TARGET: ${{ secretes.TARGET_DIR }}
 

